### PR TITLE
Delete Announcement section

### PR DESCRIPTION
**Pull request by OjesviPandita**
Deleting this file as there is a new file for News and announcements.

### CODE REVIEW

**Comment by thekirankumar** [comment]
Where will this announcement go ?

**Comment by OjesviPandita** [comment]
There is a new file for News and announcements. Every news or announcement will be added there.

**Comment by OjesviPandita** [comment]
This is for the preview branch. I guess, we can safely delete this file for now. If really required, we can add later. Also, I will check the update and make changes in the other announcement file.

**Comment by thekirankumar** [comment]
Okay, once u make announcement changes, i'll merge

**Comment by OjesviPandita** [comment]
Ok, sure

**Pull request merged**
